common:
    secret:
        data:
            token: ENC[AES256_GCM,data:KLRjNw6rlBKP6iT2FPtAcS8IyPA5,iv:w+uMXEfbHOSSpuKkasm6JkaXG90oGzyC/5eS1wNixs4=,tag:vX0ddCr2Ic9fRnU3YqXQ7A==,type:str]
sops:
    age:
        - recipient: age13u3fatj0c9dh04pvqf0qhpq96kr8zwn0kvaez0mej2mmgzvte3rsua9ey6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNDNhUzU1OXBXbEY5dXJq
            SWplZStaR1BObVVtbTBnNDl3bjFPQ3F3bjEwCkN5emFhKzZmZDZ4cTRFQzQvYlVj
            MFNTclQ1Q0VQTVhhU3ppRWRVYXBpUTAKLS0tIGhWblZPY0JIYnk0WU40WWdPZUNo
            YW5hMXArM1k5TjVNSUo2Wlg1bkRQOUUKwz3QNgz1BmT4Jae1ZiD8ooEehirPO9oz
            T3oN5Bmrm5NhIhc7Q5WOK42UbjITw1SE52hTqQ0x7h8KA3kWozccrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T19:25:33Z"
    mac: ENC[AES256_GCM,data:N3lm7uygNHUQqccR5R2ftHFN0YZctmdadiknouVROYNfBf0iP4QIjgxpAjODJvHXhqZzPFtFco+m7A6a9VhTkwa+KzWFiJJqPUYPRyGob+3eXsKMYeMUaNNVdMVuZRhQEZqUzuq6rhUA1+UzhzL2aOOjyxqFIpKnYVKFQWgBjgQ=,iv:pIYXFCqdJPnfGsoLqp4t/QInH1aU2A2vEv3CspHBQDM=,tag:9ktBahhOnyzot/7aQ6YL6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
